### ISSUE TITLE
Draft of curriculum

### ISSUE THREAD

**Issue by bkamapantula** [coderplex/LearnDataScience#2]
This is a draft of curriculum. Will improve it in the next few days.

- Introduction
  - Aspects
    - Analysis
      - Descriptive analytics
      - Diagnostic analytics
      - Prescriptive analytics
      - Predictive analytics
      - Machine learning
      - Deep learning
      - Artificial intelligence
    - Communication
      - Dashboards
      - Publications
      - Reports
      - Articles
- The role of software engineering
  - Version control
    - Software
      - git, https://try.github.io/
      - Understanding git
        - [Part 1](https://hackernoon.com/understanding-git-fcffd87c15a3)
        - [Part 2](https://hackernoon.com/understanding-git-2-81feb12b8b26)
    - Data
- Tools of the trade
  - Infrastructure
    - Azure
    - AWS
    - GCP
    - On-premise
  - Programming/Scripting
    - Python
      - [Introduction to Python](http://introtopython.org/)
      - Pandas
        - [Introduction to Pandas](https://github.com/jupyter/jupyter/wiki/A-gallery-of-interesting-Jupyter-Notebooks#pandas-for-data-analysis)
          - [What is a DataFrame?](https://github.com/Tanu-N-Prabhu/Python/blob/master/Pandas/Pandas_DataFrame.ipynb)
          - [Data manipulation with Pandas](https://nbviewer.jupyter.org/github/Tanu-N-Prabhu/Python/blob/master/Manipulating_the_data_with_Pandas_using_Python.ipynb)
    - R
      - [Introduction to R online](https://www.datacamp.com/courses/free-introduction-to-r)
    - Julia
    - [Learn SQL](https://github.com/NUKnightLab/sql-mysteries)
  - Collaboration
    - JupyterHub
      - [Deploying JupyterHub](https://jupyterhub.readthedocs.io/en/latest/gallery-jhub-deployments.html)
      - Jupyter notebooks
    - [Google colab](https://research.google.com/colaboratory/)
    - Azure notebooks
    - Kaggle
  - https://web.stanford.edu/class/cs102/

Feedback open from 18th November.

**Comment by duttakapil** [comment]
Which all resources and recommendations from here should we add to our main curriculum @bkamapantula?

**Comment by bkamapantula** [comment]
@duttakapil these two should do

- Learn SQL
- https://try.github.io

**Comment by duttakapil** [comment]
I would suggest http://jlord.us/git-it/ instead of try.github.io
